---
name: 'test'

data_dir: '/home/kwolters/sp/data/'
output_dir: '/home/kwolters/sp/project/custom-tuple/snapshots/'
batch_size: 16

num_inputs: 3
num_outputs: 2

train_keys: '/home/kwolters/sp/input/time_diff/train/odo_image_keys.txt'
train_labels: '/home/kwolters/sp/input/time_diff/train/odo_image_labels.txt'
test_keys: '/home/kwolters/sp/input/time_diff/test/odo_image_keys.txt'
test_labels: '/home/kwolters/sp/input/time_diff/test/odo_image_labels.txt'

backbone: '/home/kwolters/sp/project/custom-tuple/generate/networks/caffenet_opn.prototxt'
network: '/home/kwolters/sp/project/custom-tuple/generate/networks/opn3.prototxt'

visualize: True
vis_iter: 512

base_lr: 0.01
weight_decay: 0.001
step_value: [4000, 8000, 16000]
iter_size: 8